### ISSUE TITLE
map failed to compile

### ISSUE THREAD

**Issue by Jds1234** [ata4/bspsrc#10]
log error:

[info] Loading Z:\BackedUpStuff\SteamStuff\maps(any)\hl2maps\rp_mecklenburg.bsp
[error] BspSource: Can't load Z:\BackedUpStuff\SteamStuff\maps(any)\hl2maps\rp_mecklenburg.bsp, caused by java.io.IOException: Map failed
    at sun.nio.ch.FileChannelImpl.map(Unknown Source)
    at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:136)
    at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:150)
    at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:214)
    at info.ata4.bsplib.BspFile.load(BspFile.java:116)
    at info.ata4.bsplib.BspFile.load(BspFile.java:178)
    at info.ata4.bspsrc.BspSource.decompile(BspSource.java:98)
    at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
    at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:361)
Caused by: java.lang.OutOfMemoryError: Map failed
    at sun.nio.ch.FileChannelImpl.map0(Native Method)
    ... 9 more

[info] Processed 1 file(s) in 0.2050 seconds

link to map:

https://www.dropbox.com/s/e3yu41rtfpvd4uj/rp_mecklenburg.bsp?dl=0

**Comment by xhalo32** [comment]
i have the same problem.

**Comment by xhalo32** [comment]
i was able to decompile maps earlier but not anymore?

**Comment by fakelag28** [comment]
Eng:
If you are still experiencing this problem, please completely reinstall Java and BSPDecompile
Ru:
Если вы ещё сталкиваетесь с этой проблемой, полностью переустановите Java и BSPDecompile
