### ISSUE TITLE
CSGO MAP: Unequal amount of areaportal entities and areaportal brushes. Falling back to 'Manual' method(And then decompiling error)

### ISSUE THREAD

**Issue by tankirules** [ata4/bspsrc#107]
BspSource: Decompiling error, caused by java.lang.IllegalStateException: Duplicate key 0.9999993319456935
	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source)
	at java.util.HashMap.merge(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.areaportalBrushProb(AreaportalMapper.java:222)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.manualMapping(AreaportalMapper.java:110)
	at info.ata4.bspsrc.util.AreaportalMapper.access$100(AreaportalMapper.java:27)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.lambda$static$0(AreaportalMapper.java:296)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.map(AreaportalMapper.java:306)
	at info.ata4.bspsrc.util.AreaportalMapper.getApBrushMapping(AreaportalMapper.java:266)
	at info.ata4.bspsrc.modules.entity.EntitySource.<init>(EntitySource.java:97)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:62)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:159)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

**Comment by rihi** [comment]
The code that caused that Exception was already changed up quite a bit since v1.4, so this may already be fixed.
Can you share which map you tried decompiling?

**Comment by rihi** [comment]
The issue has now been fixed with version 1.4.1.
If your problem is not resolve with that new version, feel free to write here and I'll have another look at the problem.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
