### ISSUE TITLE
Is it possible to get an example of bspsrc cli.

### ISSUE THREAD

**Issue by rushadantia** [ata4/bspsrc#109]
I for the life of me cannot get the cli to work. Everytime i try to execute it with flags it just launches the GUI application. Is it possible to get an example of how to use it for smart embed extracting. For example I have a bsp "csgo_test.bsp" , what do i need to run to get a .vmf and all the embedded files extracted. Any help would be really appreciated. Thank you so much!

**Comment by xDShot** [comment]
`$ java -jar bspsrc-1.4.0-SNAPSHOT.jar -help`

**Comment by rushadantia** [comment]
This works fine when invoking from either WSL or Windows commandline. However when I try to execute it from an application I am replied with this.

```
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at info.ata4.bspsrc.gui.BspSourceFrame.<init>(BspSourceFrame.java:75)
        at info.ata4.bspsrc.gui.BspSourceFrame$1.run(BspSourceFrame.java:69)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I have tried running the jar from the application as headless but still get the same error. The application I currently trying to execute the jar file from is a nodejs application. 

```node 
function exec_cmd(cmd, callback) {
	console.log("EXECUTING: " + cmd)
    var child = require('child_process').exec(cmd)
    child.stdout.pipe(process.stdout)
    child.on('exit', () => {
        callback()
    })
}

const file_name = "myfile.bsp"

exec_cmd('java -jar ./maps/' + file_name + "/bspsrc.jar ./maps/" + file_name + "/" + file_name + " -unpack_embedded", () => {
       console.log('unpacked' + file_name)
})
```

However running this fails silently. I have tried everything from removing the .jar in the command to writing a bash script to run the application however everything fails. Do you have any idea on how to remedy this? Any help would be very much appreciated. Thank you

**Comment by rihi** [comment]
This is the code in question, that handles the launching of the cli:
https://github.com/ata4/bspsrc/blob/c155838b7be4da1446ed319b64ce22ed51d14330/src/main/java/info/ata4/bspsrc/BspSourceLauncher.java#L27-L31

My guess is that because you're are launching the application in nodejs, using the `child_process` module, there is no console attached to the java process. This results in the gui being launched instead.

You should be able to just use this command instead, which directly calls the cli instead of the launcher:
`java -cp bspsrc.jar info.ata4.bspsrc.cli.BspSourceCli`

**Comment by rushadantia** [comment]
This was absolutely the way to do it. Thank you so much for your time and putting up with my questions. I really REALLY appreciate all of the help.

**Comment by rushadantia** [comment]
https://gfycat.com/impressiveadvancedhylaeosaurus Here is what I made with the tool. Once again thank you for your help
