### ISSUE TITLE
[error] BspSource: Decompiling error, caused by java.lang.IllegalStateException: Duplicate key 0.9999841065765562

### ISSUE THREAD

**Issue by Spygineer2** [ata4/bspsrc#126]
I was trying to decompile map bm_c1a4b.bsp from Black Mesa using the latest version of BSPSource, and I get the following error:
```
[info] BSP version: 20
[info] Game: Black Mesa
[info] Unequal amount of areaporal entities and areaportal brushes. Falling back to 'Manual' method
[error] BspSource: Decompiling error, caused by java.lang.IllegalStateException: Duplicate key 0.9999841065765562
	at java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source)
	at java.util.HashMap.merge(Unknown Source)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.areaportalBrushProb(AreaportalMapper.java:222)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.manualMapping(AreaportalMapper.java:110)
	at info.ata4.bspsrc.util.AreaportalMapper.access$100(AreaportalMapper.java:27)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.lambda$static$0(AreaportalMapper.java:296)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.map(AreaportalMapper.java:306)
	at info.ata4.bspsrc.util.AreaportalMapper.getApBrushMapping(AreaportalMapper.java:266)
	at info.ata4.bspsrc.modules.entity.EntitySource.<init>(EntitySource.java:97)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:62)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:159)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
```
I tried decompiling a few other maps from Black Mesa and they seem to work fine. It is just this one in particular that won't work.

**Comment by rihi** [comment]
Hey, I believe your issue is what has been fixed with 1.4.1.
If your problem is not resolve with that new version, feel free to write here and I'll have another look at the problem.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
