### ISSUE TITLE
[Error] Exception thrown when recompiling directory

### ISSUE THREAD

**Issue by Triggerhacks** [ata4/bspsrc#127]
Hi, I've been trying to decompile an entire directory using the `-r` argument. For some reason it keeps throwing the following exception:
`[error] BspSourceCli: Fatal BSPSource error, caused by java.lang.UnsupportedOperationException: Syntax 'blob' not recognized
        at java.base/sun.nio.fs.WindowsFileSystem.getPathMatcher(WindowsFileSystem.java:273)
        at info.ata4.bspsrc.cli.BspSourceCli.getConfig(BspSourceCli.java:371)
        at info.ata4.bspsrc.cli.BspSourceCli.run(BspSourceCli.java:214)
        at info.ata4.bspsrc.cli.BspSourceCli.main(BspSourceCli.java:74)
        at info.ata4.bspsrc.BspSourceLauncher.main(BspSourceLauncher.java:30)`

Any help/solution is appreciated! Thank you in advance.

**Comment by rihi** [comment]
This should be fixed now with the new release.
Let me if you still run into any issues.
