### ISSUE TITLE
Trying to decompile Half Life 2 Lost Coast map, error: BspSource: Decompiling error, caused by java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by trudruchocolatemilk** [ata4/bspsrc#134]
There are 4 maps in the HL2 lost coast folder, and only the background one wants to decompile correctly, if anyone can help that'd be nice, thanks.

> [error] BspSource: Decompiling error, caused by java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:141)
	at info.ata4.bspsrc.util.AreaportalMapper.lambda$manualMapping$14(AreaportalMapper.java:148)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
	at info.ata4.bspsrc.util.AreaportalMapper.manualMapping(AreaportalMapper.java:143)
	at info.ata4.bspsrc.util.AreaportalMapper.access$100(AreaportalMapper.java:27)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.lambda$static$0(AreaportalMapper.java:296)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.map(AreaportalMapper.java:306)
	at info.ata4.bspsrc.util.AreaportalMapper.getApBrushMapping(AreaportalMapper.java:266)
	at info.ata4.bspsrc.modules.entity.EntitySource.<init>(EntitySource.java:97)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:62)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:159)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

**Comment by rihi** [comment]
The bug in question has already been fixed in #89 and merged into the repository. However, currently no offiical release exists with the fix included, so you'd have build the program yourself if you want to use it now.

**Comment by rihi** [comment]
Hey, the fix has now been released with version 1.4.1.
If your problem is not resolve with that new version, feel free to write here and I'll have another look at the problem.
You can get the release on the [releases page](https://github.com/ata4/bspsrc/releases).
