### ISSUE TITLE
map failed to compile

### ISSUE THREAD

**Issue by scaredll** [ata4/bspsrc#138]
[error] BspSource: Can't load C:\Users\root\Desktop\testmap_v10.bsp, caused by java.io.IOException: Map failed
	at sun.nio.ch.FileChannelImpl.map(Unknown Source)
	at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:181)
	at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:195)
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:216)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
Caused by: java.lang.OutOfMemoryError: Map failed
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	... 9 more

How to fix it?

**Comment by rihi** [comment]
BspSource tries to load the whole bsp into ram. The error you got indicates that there wasn't enough ram available to do that.
Depending on the file size of the bsp, you should be able to just close some programs to free up more memory.

**Comment by JonkaJake** [comment]
I'm still getting this error even with 11 of my 16gb free?

**Comment by JonkaJake** [comment]
[error] BspSource: Can't load D:\SteamLibrary\steamapps\workshop\content\4000\2028581413\temp\maps\rp_southside_day.bsp, caused by java.io.IOException: Map failed
	at sun.nio.ch.FileChannelImpl.map(Unknown Source)
	at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:181)
	at info.ata4.io.buffer.ByteBufferUtils.openReadOnly(ByteBufferUtils.java:195)
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:216)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
Caused by: java.lang.OutOfMemoryError: Map failed
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	... 9 more

**Comment by rihi** [comment]
Hm, yeah I don't know what else could be causing that. If you could share a map where that happens to you, I could try replicating it on my pc.
