### ISSUE TITLE
map decompiling error

### ISSUE THREAD

**Issue by alvaius** [ata4/bspsrc#148]
was trying to port a map to SFM, didn't work so i tried decompiling the map on bspsource but it gave me this error:

[error] BspSource: Can't load F:\bspsrc_1.4.1\scpsl_map.bsp, caused by info.ata4.bsplib.BspException: Invalid or missing header
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:223)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

not sure why this is happening, other maps i've decompiled seem to work fine, any fixes?

**Comment by ByDexterTR** [comment]
after making the file name "filename.bsp.zip", extract it from the archive and try again.

**Comment by rihi** [comment]
Hard to say from just the error. My guess is that the file is somehow corrupted. You can test by trying to load the bsp in game and see if that works.

**Comment by ReformedPony** [comment]
I had the same problem. What worked for me was instead of using GMad Extractor to unpack the .gma files, I used the gmad.exe that comes with Garry's Mod to do that, then used bspsrc to decompile the bsp, and it worked.
