### ISSUE TITLE
BspSource: Decompiling error, caused by java.lang.IllegalArgumentException: newLimit

### ISSUE THREAD

**Issue by JarodSCP** [ata4/bspsrc#150]
I have this error when I try to decompile this maps: https://steamcommunity.com/sharedfiles/filedetails/?id=2845503123

[error] BspSource: Decompiling error, caused by java.lang.IllegalArgumentException: newLimit < 0: (-2138374787 < 0)
	at java.base/java.nio.Buffer.createLimitException(Buffer.java:395)
	at java.base/java.nio.Buffer.limit(Buffer.java:369)
	at java.base/java.nio.ByteBuffer.limit(ByteBuffer.java:1529)
	at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:330)
	at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:73)
	at info.ata4.io.buffer.ByteBufferUtils.getSlice(ByteBufferUtils.java:255)
	at info.ata4.bsplib.BspFile.loadLumps(BspFile.java:349)
	at info.ata4.bsplib.BspFile.load(BspFile.java:160)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

**Comment by rihi** [comment]
The link to the workshop map doesn't seem to work anymore. If you could update it, I would have look at it.

**Comment by alexiscoutinho** [comment]
@rihi I think I have a pretty similiar issue:
```
Error occurred decompiling '<bsp file path...>'
java.lang.IllegalArgumentException: newLimit > capacity: (178647 > 177872)
	at java.nio.Buffer.createLimitException(Buffer.java:406) ~[?:?]
	at java.nio.Buffer.limit(Buffer.java:380) ~[?:?]
	at java.nio.ByteBuffer.limit(ByteBuffer.java:1565) ~[?:?]
	at java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:338) ~[?:?]
	at java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:73) ~[?:?]
	at info.ata4.io.buffer.ByteBufferUtils.getSlice(ByteBufferUtils.java:255) ~[bspsrc.jar:?]
	at info.ata4.bspsrc.lib.lump.LumpFile.load(LumpFile.java:95) ~[bspsrc.jar:?]
	at info.ata4.bspsrc.lib.BspFile.loadLumpFiles(BspFile.java:424) ~[bspsrc.jar:?]
	at info.ata4.bspsrc.decompiler.BspSource.decompile(BspSource.java:163) ~[bspsrc.jar:?]
	at info.ata4.bspsrc.decompiler.BspSource.decompile(BspSource.java:128) ~[bspsrc.jar:?]
	at info.ata4.bspsrc.decompiler.BspSource.lambda$run$0(BspSource.java:94) ~[bspsrc.jar:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```
[labirinferno_parte1.bsp.txt](https://github.com/ata4/bspsrc/files/14718337/labirinferno_parte1.bsp.txt)

**Comment by alexiscoutinho** [comment]
A few years ago I managed to decompile it btw, but now I can't get it back.

**Comment by rihi** [comment]
The problem seems to be something related to external lump files. When you have name `<filename>_l_<number>.lmp`, bspsrc tries to load them as well. For some reason this fails.
If you could also provide the external lump file(s), I can hopefully figure out what the problem is.

**Comment by alexiscoutinho** [comment]
> Your problem seems to be something related to external lump files.

You're right! Indeed a problematic external lump was affecting the original bsp decompilation. The external lump was manually edited and had an excess size according to the header (178627, which becomes 178647 when including the 20 bytes from the header itself). The real size of the lump file is indeed 177872. I had forgotten to adjust the size in the lump header when I finished experimenting as, ingame, no error shows up. Here is the file btw: [labirinferno_parte1_l_0.lmp.txt](https://github.com/ata4/bspsrc/files/14813176/labirinferno_parte1_l_0.lmp.txt).

But most importantly, I did not know a lump in the same directory as the target bsp would also take part in the decompilation. I thought I had to explicitly include it in the Files list. Well, now I know. But I would suggest that you make it so that mismatching lump sizes are treated as a warning and not error, i.e. rely on the real lump size. Furthermore, it would be nice to clarify that the 'Load lump files' option reads lumps with the same name and in the **same directory**. As I hinted, when I read "external" in the tooltip, I understood that the lump files could be in any directory as long as you included them in the Files list. ;)
