### ISSUE TITLE
tf2's pd_watergate cannot extract embedded files??

### ISSUE THREAD

**Issue by Rahlii** [ata4/bspsrc#19]
Here is the log.

[warning] BspFile: Negative game lump length -12,742,144 in prpd, assuming 0
[warning] BspSource: Can't extract embedded files, caused by org.apache.commons.compress.archivers.zip.UnsupportedZipFeatureException: unsupported feature method 'LZMA' used in entry materials/maps/pd_watergate/brick/blendtestwall001_watergate_wvt_patch.vmt
    at org.apache.commons.compress.archivers.zip.ZipUtil.checkRequestedFeatures(ZipUtil.java:325)
    at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.read(ZipArchiveInputStream.java:386)
    at java.io.InputStream.read(Unknown Source)
    at java.nio.file.Files.copy(Unknown Source)
    at java.nio.file.Files.copy(Unknown Source)
    at info.ata4.bsplib.PakFile.unpack(PakFile.java:89)
    at info.ata4.bsplib.PakFile.unpack(PakFile.java:56)
    at info.ata4.bsplib.PakFile.unpack(PakFile.java:45)
    at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
    at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
    at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:361)

**Comment by ata4** [comment]
Interesting... the embedded zip file uses the LZMA compression method. Didn't even know that LZMA is possible within ordinary zip files. A workaround would be to extract the entire zip file with BSPInfo and then use 7z to extract its contents.

**Comment by imyoutubefan2** [comment]
turns out gcfscape can open bsp files. I grabbed the zip out of it that way
already. Thanks.
