### ISSUE TITLE
The GoldSrc format is not supported

### ISSUE THREAD

**Issue by elixir1349** [ata4/bspsrc#29]
This map of half life 1 is impossibile to decompile, not only, neither open it
https://www.dropbox.com/s/cr9c9rb50ki0hiu/crossfiretest.bsp?dl=1

Error is this

`[info] Loading C:\Users\asus\Desktop\crossfirechina.bsp
[error] BspSource: Can't load C:\Users\asus\Desktop\crossfirechina.bsp, caused by info.ata4.bsplib.BspException: The GoldSrc format is not supported
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:251)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:98)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:362)
[info] Processed 1 file(s) in 0,2140 seconds`

![cross](https://cloud.githubusercontent.com/assets/3471861/22272839/0be584f4-e29d-11e6-8c06-1c7174a6f915.png)

**Comment by ata4** [comment]
Well, it's in the error message: BSPSource doesn't support Half-Life 1 maps (HL1 uses the GoldSrc engine), because it uses a file format that is incompatible with the Source engine. You have to use a matching decompiler for that engine, like BSP2MAP.
