### ISSUE TITLE
Buffer Underflow while decompiling ttt_nuclear_power_v3

### ISSUE THREAD

**Issue by end360** [ata4/bspsrc#32]
When I try to decompile ttt_nuclear_power_v3 I get the following error and a corrupted vmf:
`[error] BspFileReader: Lump reading error in sprp, caused by java.io.IOException: java.nio.BufferUnderflowException
	at info.ata4.util.io.ByteBufferIO.readFloat(ByteBufferIO.java:191)
	at info.ata4.bsplib.lump.LumpIO.readVector3f(LumpIO.java:59)
	at info.ata4.bsplib.struct.DStaticPropV4.read(DStaticPropV4.java:45)
	at info.ata4.bsplib.struct.DStaticPropV5.read(DStaticPropV5.java:30)
	at info.ata4.bsplib.struct.DStaticPropV8.read(DStaticPropV8.java:34)
	at info.ata4.bsplib.struct.DStaticPropV9.read(DStaticPropV9.java:30)
	at info.ata4.bsplib.struct.DStaticPropV10.read(DStaticPropV10.java:30)
	at info.ata4.bsplib.BspFileReader.loadStaticProps(BspFileReader.java:332)
	at info.ata4.bsplib.BspFileReader.loadAll(BspFileReader.java:76)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:112)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:360)
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Unknown Source)
	at java.nio.DirectByteBuffer.getFloat(Unknown Source)
	at info.ata4.util.io.ByteBufferIO.readFloat(ByteBufferIO.java:189)
	... 11 more
`
It's the very first thing after it grabs the static prop leaves (1000) and before it loads LUMP_CUBEMAPS.
Full log is available here: https://gist.github.com/end360/af52a46c4f82756c964f40aa854dd39c
Very sad, I wanted to find out where that secret backdoor button is.

**Comment by end360** [comment]
Almost forgot, copy of the map can be found here: http://wvttt.site.nfoservers.com/server/maps/ttt_nuclear_power_v3.bsp.bz2
