### ISSUE TITLE
Errors from apex .bsp 

### ISSUE THREAD

**Issue by JuicySoup** [ata4/bspsrc#59]
Getting these errors from the apex .bsp map file: 
```
[error] BspFileReader: Lump reading error in LUMP_MODELS, caused by java.io.IOException: 32 bytes remaining
	at info.ata4.bsplib.BspFileReader.checkRemaining(BspFileReader.java:907)
	at info.ata4.bsplib.BspFileReader.loadLump(BspFileReader.java:845)
	at info.ata4.bsplib.BspFileReader.loadModels(BspFileReader.java:231)
	at info.ata4.bsplib.BspFileReader.loadAll(BspFileReader.java:81)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:114)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:364)

[error] BspFileReader: Lump reading error in LUMP_TEXDATA, caused by java.io.IOException: 16 bytes remaining
	at info.ata4.bsplib.BspFileReader.checkRemaining(BspFileReader.java:907)
	at info.ata4.bsplib.BspFileReader.loadLump(BspFileReader.java:845)
	at info.ata4.bsplib.BspFileReader.loadTexData(BspFileReader.java:511)
	at info.ata4.bsplib.BspFileReader.loadAll(BspFileReader.java:85)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:114)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:67)
	at info.ata4.bspsrc.gui.BspSourceFrame$5.run(BspSourceFrame.java:364)

[warning] BspFileReader: Couldn't find static prop struct for version 47
[warning] BspFileReader: Falling back to static prop v4
[error] BspSource: Decompiling error, caused by java.lang.IllegalArgumentException: Illegal Capacity: -1
	at java.base/java.util.ArrayList.<init>(Unknown Source)
	at info.ata4.bsplib.BspFileReader.lou
```

**Comment by Stiffy360** [comment]
Apex's BSP format is way waaaaaay different than source's og format. Map probably wouldn't even load into hammer if you could decompile it.

**Comment by harzival** [comment]
There is a mod in the works that's now playable with custom servers and scripting access, the next huge milestone IMO is custom maps, they have made headway and have a custom vpk.exe that extracted me a bsp from one of the main maps. I get this error aswell, and yea any hammer we have wont load it, but if we can decompile them to vmf it might get us closer to fixing that issue.

**Comment by rihi** [comment]
Because as far as I know, apex bsp format is way different from the kind of formats bspsrc handles, it's very unlikely that apex is ever really "supported". I won't close this though, because I would have to have a closer look at its bsp format to really be able to say if bspsrc can support/if it makes sense to support it.
