### ISSUE TITLE
Support for Counter-Strike Online 2 and some suggestions.

### ISSUE THREAD

**Issue by KudDroid** [ata4/bspsrc#77]
Examples:
[de_train.zip](https://github.com/ata4/bspsrc/files/3805217/de_train.zip)
[de_inferno.zip](https://github.com/ata4/bspsrc/files/3805220/de_inferno.zip)

Also this game use a custom texture call `toolsshadowblock` which covering the whole map.I doubt this texture only useful for CSO2. I wondering can bspsrc remove this texture during the decompile process?
Thanks!

**Comment by the3dsean** [comment]
Seconding this, when trying to run the CSO2 version of de_train through BSPSRC, this error comes up:
`[error] BspSource: Can't load <cso2 directory>\Data\cso2 extract\cstrike\maps\de_train.bsp, caused by info.ata4.bsplib.BspException: Unknown file ident: -1721796365 (óx_™)
	at info.ata4.bsplib.BspFile.createBuffer(BspFile.java:286)
	at info.ata4.bsplib.BspFile.load(BspFile.java:118)
	at info.ata4.bsplib.BspFile.load(BspFile.java:180)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:107)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

`
