### ISSUE TITLE
Invalid areaportals

### ISSUE THREAD

**Issue by xtance** [ata4/bspsrc#85]
Hello, I'm unable to decompile a map, vmf comes out empty. 

```
[warning] AreaportalMapper: Invalid areaportals, map was probably compiled with errors! Errors should be expected
[info] Unequal amount of areaporal entities and areaportal brushes. Falling back to 'Manual' method
[error] BspSource: Decompiling error, caused by java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at java.util.Collections$UnmodifiableList.get(Unknown Source)
	at info.ata4.bspsrc.util.Winding.get(Winding.java:595)
	at info.ata4.bspsrc.util.Winding.buildPlane(Winding.java:444)
	at info.ata4.bsplib.util.VectorUtil.internalMatchingAreaPercentage(VectorUtil.java:51)
	at info.ata4.bsplib.util.VectorUtil.matchingAreaPercentage(VectorUtil.java:31)
	at info.ata4.bspsrc.util.AreaportalMapper.lambda$areaportalBrushProb$18(AreaportalMapper.java:219)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.areaportalBrushProb(AreaportalMapper.java:222)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at info.ata4.bspsrc.util.AreaportalMapper.manualMapping(AreaportalMapper.java:110)
	at info.ata4.bspsrc.util.AreaportalMapper.access$100(AreaportalMapper.java:27)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.lambda$static$0(AreaportalMapper.java:296)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.map(AreaportalMapper.java:306)
	at info.ata4.bspsrc.util.AreaportalMapper.getApBrushMapping(AreaportalMapper.java:266)
	at info.ata4.bspsrc.modules.entity.EntitySource.<init>(EntitySource.java:97)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:62)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:159)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)

[info] Processed 1 file(s) in 0,6450 seconds
```

**Comment by rihi** [comment]
Hmmm, yeah... Seems like the map you're trying to decompile has some weird/broken areaportals in it. And because I made a mistake with the error handling, this causes the whole decompiler to crash. Should be an easy fix.

Can you provide the bsp, you were trying to decompile? Would make it easier for me to test, if my changes now work correctly.

**Comment by xtance** [comment]
[de_dust2002.zip](https://github.com/ata4/bspsrc/files/4036812/de_dust2002.zip)
 Yes, here it is
