### ISSUE TITLE
 Decompiling error, caused by java.util.NoSuchElementException: No value present when decompiling d2_lostcoast.bsp

### ISSUE THREAD

**Issue by Yetoo1** [ata4/bspsrc#88]
When I attempt to decompile d2_lostcoast.bsp (from Half-Life 2: Lost Coast) with default settings I get the following error:
`[error] BspSource: Decompiling error, caused by java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at info.ata4.bspsrc.util.AreaportalMapper.lambda$manualMapping$14(AreaportalMapper.java:148)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
	at info.ata4.bspsrc.util.AreaportalMapper.manualMapping(AreaportalMapper.java:143)
	at info.ata4.bspsrc.util.AreaportalMapper.access$100(AreaportalMapper.java:27)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.lambda$static$0(AreaportalMapper.java:296)
	at info.ata4.bspsrc.util.AreaportalMapper$ApMappingMode.map(AreaportalMapper.java:306)
	at info.ata4.bspsrc.util.AreaportalMapper.getApBrushMapping(AreaportalMapper.java:266)
	at info.ata4.bspsrc.modules.entity.EntitySource.<init>(EntitySource.java:97)
	at info.ata4.bspsrc.modules.BspDecompiler.<init>(BspDecompiler.java:62)
	at info.ata4.bspsrc.BspSource.decompile(BspSource.java:159)
	at info.ata4.bspsrc.BspSource.run(BspSource.java:72)
	at info.ata4.bspsrc.gui.BspSourceFrame$4.run(BspSourceFrame.java:359)
`

Here is the debug output:
http://archive.is/K9aZK

The map file is created but it's empty (0 kb). I tried decompiling one other map with default settings (background_02 from hl2), but that generated successfully with no errors.

BSPSource Version:
1.4.0

Java version:
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)

**Comment by rihi** [comment]
The error was something I oversaw when writing the algorithm for reallocating areaportals manually. I've fixed it now and created a new pull request.
Sadly, there isn't workaround for this bug, so you'd have to wait for the fix to be officially released. If you need the map now though, I could decompile it for you and give you the vmf. Or if you're familiar with java, you could also just build the project yourself from my pr.
